# Stage 1: Build avec SDK
FROM chainguard/dotnet-sdk:latest-dev AS build
ARG TARGETARCH

WORKDIR /tmp/build

COPY HelloWorldApi/*.csproj ./
RUN dotnet restore -a $TARGETARCH

COPY HelloWorldApi/ ./

RUN dotnet publish -c Release -a $TARGETARCH --no-restore -o /tmp/build/output

# Stage 2: Runtime minimal Chainguard
FROM chainguard/aspnet-runtime:latest
WORKDIR /app

COPY --from=build /tmp/build/output .

USER 1000

ENTRYPOINT ["dotnet", "HelloWorldApi.dll"]
