# Stage 1: Build de l'application avec Node.js 22
FROM node:22 AS build-env

WORKDIR /app

COPY node-api/package*.json ./
COPY node-api/tsconfig.json ./
RUN npm ci

COPY node-api/src/ ./src/
RUN npm run build

# Stage 2: Image finale avec Google Distroless
FROM gcr.io/distroless/nodejs22-debian12

WORKDIR /app

COPY --from=build-env /app/node_modules ./node_modules
COPY --from=build-env /app/dist ./dist
COPY --from=build-env /app/package*.json ./

CMD ["dist/server.js"]

